apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: us-central1-docker.pkg.dev/spot-hunter-427512/microservices/auth
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "250m"
            memory: "1Gi"
            ephemeral-storage: "500Mi"
          requests:
            cpu: "250m"
            memory: "1Gi"
            ephemeral-storage: "500Mi"
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: auth.settings
        - name: PORT
          value: "8000"
