apiVersion: v1
kind: Service
metadata:
  name: authentication2
spec:
  type: LoadBalancer
  selector:
    app: authentication2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30960
